// 自動產生的程式碼。請勿編輯。
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "我的影像":return img`
..............................
............ccccc.............
...........cbbbbbc............
........ccccccccccccc.........
.......cccbbbbcbbbbccc........
.......cbcbbbbcbbbbcbc........
.......cbcdddddddddcbc........
.......ccdddddddddddcc........
.........ddd2ddd2ddd..........
.........ddddd2ddddd..........
.........dddd2d2dddd..........
.......ccccccccccccccc........
.......cbcbbbbcbbbbcbc........
.ff...cbbcbbbbcbbbbcbbc...ff..
...ff.cbbcbbbbcbbbbcbbc.ff....
.....fcbbbcbbbcbbbcbbbcf......
.......cbbcbbbcbbbcbbc........
.......cbbcbbbcbbbcbbc........
.......cbbcbbbcbbbcbbc........
........cbbcbbcbbcbbc.........
........cbbcbbcbbcbbc.........
........cbbcbbcbbcbbc.........
.........cbbcbcbcbbc..........
..........ccccccccc...........
..........f.......f...........
.......ffff.......ffff........
......fffff.......fffff.......
......fffff.......fffff.......
..............................
..............................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// 自動產生的程式碼。請勿編輯。
